// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/blog/[slug].tsx";
import * as $2 from "./routes/blog/index.tsx";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/Fancy.tsx";
import * as $$1 from "./islands/Orbits.tsx";
import * as $$2 from "./islands/PostCommentForm.tsx";
import * as $$3 from "./islands/Salesforce.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/blog/[slug].tsx": $1,
    "./routes/blog/index.tsx": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/Fancy.tsx": $$0,
    "./islands/Orbits.tsx": $$1,
    "./islands/PostCommentForm.tsx": $$2,
    "./islands/Salesforce.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
